# Generated by Django 4.2.2 on 2023-06-15 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('location', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EntertainmentProperty',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edificio.property')),
                ('type', models.CharField(default='entertainment', max_length=50)),
            ],
            bases=('edificio.property',),
        ),
        migrations.CreateModel(
            name='IndustrialProperty',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edificio.property')),
                ('type', models.CharField(default='industrial', max_length=50)),
                ('industry', models.CharField(max_length=50)),
            ],
            bases=('edificio.property',),
        ),
        migrations.CreateModel(
            name='ResidentialProperty',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edificio.property')),
                ('type', models.CharField(default='residential', max_length=50)),
            ],
            bases=('edificio.property',),
        ),
    ]
