# Generated by Django 4.2.2 on 2023-06-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainmentproperty',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=43667),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='floors',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentialproperty',
            name='total_rooms',
            field=models.PositiveSmallIntegerField(default=100),
            preserve_default=False,
        ),
    ]
