# Generated by Django 4.2.2 on 2023-06-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
